// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDxM-G38CFYtCYbS3ND3fZlirLRKBOoXQc',
    appId: '1:951814205337:web:904e57267945c244f52d08',
    messagingSenderId: '951814205337',
    projectId: 'kuber-167ed',
    authDomain: 'kuber-167ed.firebaseapp.com',
    storageBucket: 'kuber-167ed.appspot.com',
    measurementId: 'G-R0QNF2TEQG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA8NgvQs8XyzK5goK3yMRB50bsYKsskVFY',
    appId: '1:951814205337:android:35b198da77b1704ff52d08',
    messagingSenderId: '951814205337',
    projectId: 'kuber-167ed',
    storageBucket: 'kuber-167ed.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBMqtm6zHJoJIcfpbzRWdM838C2zwlAOHM',
    appId: '1:951814205337:ios:8222b1c7f0b8ebcff52d08',
    messagingSenderId: '951814205337',
    projectId: 'kuber-167ed',
    storageBucket: 'kuber-167ed.appspot.com',
    androidClientId: '951814205337-6r2tfv1e0e8160ehpmq66fhd1hvp7nad.apps.googleusercontent.com',
    iosClientId: '951814205337-3f4p22bims9728nqnmfc02470bu3tn8g.apps.googleusercontent.com',
    iosBundleId: 'com.coronation.kuber',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBMqtm6zHJoJIcfpbzRWdM838C2zwlAOHM',
    appId: '1:951814205337:ios:8222b1c7f0b8ebcff52d08',
    messagingSenderId: '951814205337',
    projectId: 'kuber-167ed',
    storageBucket: 'kuber-167ed.appspot.com',
    androidClientId: '951814205337-6r2tfv1e0e8160ehpmq66fhd1hvp7nad.apps.googleusercontent.com',
    iosClientId: '951814205337-3f4p22bims9728nqnmfc02470bu3tn8g.apps.googleusercontent.com',
    iosBundleId: 'com.coronation.kuber',
  );
}
